# Generated by Django 3.0.5 on 2020-04-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamePlay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player To Move'), ('S', 'Second Player To Move'), ('W', 'First Player Wins'), ('L', 'Second Player Wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
